### ISSUE TITLE
Doesn't work with filenames with special chars

### ISSUE THREAD

**Issue by mphe** [jackguo380/vim-lsp-cxx-highlight#19]
**Describe the bug**
coc.nvim immediately throws exceptions when opening a file that contains special characters in its path. This only happens in combination with this plugin, so its not a coc.nvim bug.
The plugin works fine for paths without special characters.
According to the logs it seems like `unescape_urlencode` is buggy and incorrectly unescapes the filename, resulting in not finding the corresponding vim buffer.

**To Reproduce**
neovim + coc.nvim + ccls

```sh
mkdir c++
cd c++
nvim test.cpp
```

**coc.nvim log**
```
2020-03-09T21:22:42.833 INFO (pid:470838) [services] - registered service "languageserver.ccls"
2020-03-09T21:22:42.835 INFO (pid:470838) [services] - ccls state change: stopped => starting
2020-03-09T21:22:42.871 INFO (pid:470838) [services] - registered service "highlight"
2020-03-09T21:22:42.900 INFO (pid:470838) [plugin] - coc 0.0.75-9e9b0ad3a2 initialized with node: v13.5.0
2020-03-09T21:22:42.905 INFO (pid:470838) [language-client-index] - languageserver.ccls started with 470858
2020-03-09T21:22:42.918 INFO (pid:470838) [language-client-index] - highlight started with 470859
2020-03-09T21:22:42.968 INFO (pid:470838) [services] - ccls state change: starting => running
2020-03-09T21:22:42.979 INFO (pid:470838) [services] - service languageserver.ccls started
2020-03-09T21:22:42.994 ERROR (pid:470838) [server] - unhandledRejection  Promise {
  <rejected> Error: request error nvim_call_function - buffer does not exist!
      at /home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:14243:32
      at NvimTransport.parseMessage (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:10847:17)
      at DecodeStream.<anonymous> (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:10817:18)
      at DecodeStream.emit (events.js:305:20)
      at addChunk (_stream_readable.js:341:12)
      at readableAddChunk (_stream_readable.js:316:11)
      at DecodeStream.Readable.push (_stream_readable.js:250:10)
      at DecodeStream.Transform.push (_stream_transform.js:152:32)
      at DecodeBuffer.DecodeStream.decoder.push (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:13767:12)
      at DecodeBuffer.flush (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:12757:12)
} Error: request error nvim_call_function - buffer does not exist!
    at /home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:14243:32
    at NvimTransport.parseMessage (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:10847:17)
    at DecodeStream.<anonymous> (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:10817:18)
    at DecodeStream.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at DecodeStream.Readable.push (_stream_readable.js:250:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:13767:12)
    at DecodeBuffer.flush (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:12757:12)
2020-03-09T21:22:42.996 ERROR (pid:470838) [server] - unhandledRejection  Promise {
  <rejected> Error: request error nvim_call_function - buffer does not exist!
      at /home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:14243:32
      at NvimTransport.parseMessage (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:10847:17)
      at DecodeStream.<anonymous> (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:10817:18)
      at DecodeStream.emit (events.js:305:20)
      at addChunk (_stream_readable.js:341:12)
      at readableAddChunk (_stream_readable.js:316:11)
      at DecodeStream.Readable.push (_stream_readable.js:250:10)
      at DecodeStream.Transform.push (_stream_transform.js:152:32)
      at DecodeBuffer.DecodeStream.decoder.push (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:13767:12)
      at DecodeBuffer.flush (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:12757:12)
} Error: request error nvim_call_function - buffer does not exist!
    at /home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:14243:32
    at NvimTransport.parseMessage (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:10847:17)
    at DecodeStream.<anonymous> (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:10817:18)
    at DecodeStream.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at DecodeStream.Readable.push (_stream_readable.js:250:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:13767:12)
    at DecodeBuffer.flush (/home/marvin/dotfiles/homedir/.vim/plugged/coc.nvim/build/index.js:12757:12)
2020-03-09T21:22:43.059 INFO (pid:470838) [services] - highlight server state change: starting => running
```

**vim-lsp-cxx-highlight**
```
Mon 09 Mar 2020 09:22:42 PM CET: lsp_cxx_hl beginning initialization...
Mon 09 Mar 2020 09:22:42 PM CET: vim-lsp not detected
Mon 09 Mar 2020 09:22:42 PM CET: LanguageClient-neovim not detected
Mon 09 Mar 2020 09:22:42 PM CET: coc.nvim successfully registered
Mon 09 Mar 2020 09:22:42 PM CET: nvim-lsp not detected
Mon 09 Mar 2020 09:22:42 PM CET: ccls regions:{'uri': 'file:///home/marvin/c%2B%2B/test.cpp', 'skippedRanges': []}
Mon 09 Mar 2020 09:22:42 PM CET: unescape_urlencode unescaped filename: /home/marvin/c+%2+est.cpp
Mon 09 Mar 2020 09:22:42 PM CET: ccls hl:{'uri': 'file:///home/marvin/c%2B%2B/test.cpp', 'symbols': []}
Mon 09 Mar 2020 09:22:42 PM CET: unescape_urlencode unescaped filename: /home/marvin/c+%2+est.cpp
```

**Comment by jackguo380** [comment]
Thanks for reporting this mphe. Was just a small bug in my unescape function with handling multiple escaped characters.

**Comment by mphe** [comment]
Works now, thanks for the quick fix!
